### ISSUE TITLE
疑似BUG？无法将翻译脚本替换回原文

### ISSUE THREAD

**Issue by DaBoSAMA** [jsc6924/translation-assistant#1]
汉化某部krkr引擎的老作品途中，发现“B003.ks”文件 使用“用双行文本的翻译替换脚本中的原文” 后在 输出 中会报错，如下：

> item=***.\output\B003.txt 
> labeled_line_num=10, translated_line_num=1
> Error: label not matched

本以为是汉化过程中误修改了代码，结果经测试发现，就算只对原文件使用 “将脚本提取为双行文本” 后 立刻使用  “用双行文本的翻译替换脚本中的原文”  也会报相同的错误，无关是否修改过提取出来的双行文本。

B003.ks源文件前二十行：

```
 *chapter10_0|ガラパゴスの箱舟

[msgc]
[bgi storage=white rule=rubfade_lr time=1000]
[bgi storage=black]
[bgi storage=mh rule=rubfade_lr time=1000]
[msgv]

[fadeinbgm storage=nitijou time=3500]

　晴れた爽やかな朝だ。[rl]
　昨日の夜のうちに洗濯機を回すよう予約しておいたおかげで朝の準備はスムーズだ。[rl]
[r]

[fgi storage=11]

[voice file=2094]
「わたしが干すよ」[rl]
[r]
　すでに起きていた鈴佳が笑顔で洗濯カゴを受け取ってくれる。[l]だけど今日は僕が干したい事情があった。[rl]

```

生成的B003.label前20行：
```
[#[0]#]

[msgc]
[bgi storage=white rule=rubfade_lr time=1000]
[bgi storage=black]
[bgi storage=mh rule=rubfade_lr time=1000]
[msgv]

[fadeinbgm storage=nitijou time=3500]

　[#[1]#]
　[#[2]#]
[r]

[fgi storage=11]

[voice file=2094]
[#[3]#]
[r]
　[#[4]#]
```

想要使用的汉化B003.txt前20行：
```
★0★*chapter10_0|ガラパゴスの箱舟
☆0☆*chapter10_0|加拉帕戈斯的方舟


★1★晴れた爽やかな朝だ。[rl]
☆1☆　晴朗的早晨。[rl]


★2★昨日の夜のうちに洗濯機を回すよう予約しておいたおかげで朝の準備はスムーズだ。[rl]
☆2☆　多亏昨晚提前给洗衣机定了个时，早上不至于忙得手忙脚乱。[rl]


★3★「わたしが干すよ」[rl]
☆3☆「我来晾衣服吧」[rl]


★4★すでに起きていた鈴佳が笑顔で洗濯カゴを受け取ってくれる。[l]だけど今日は僕が干したい事情があった。[rl]
☆4☆　已经早早起床了的铃佳笑着拿来了洗衣篮。[l]但出于某个原因，今天我打算自己晾这些衣服。[rl]



```

使用的dlbuild.yaml配置文件：

```
extract: #配置提取操作
  input:
    path: './input/'   #游戏原脚本所在的文件夹
    encoding: 'utf16le-bom'   #游戏脚本使用的编码格式
    ext: 'ks'              #游戏脚本的后缀名，空字符串表示全部匹配
    digits: 1               #双行文本标签中数字的长度
    items:                  #配置想提取的文本，程序会一行行读取脚本并使用正则表达式匹配
      - capture: '@Talk .*?name=(\S+)'             #描述要提取的文本
        tag: 'nme'          #双行文本中标签的前缀
        group: 1                                   #注明要提取capture中的哪个group
      - capture: '^\s*([^@\s\[\];].*)'
        tag: ''
        group: 1
  output:
    path: './output/'    #提取出来的双行文本会保存到这里
    encoding: 'utf16le-bom' #双行文本使用的编码格式

pack: #配置替换操作
  input:
    path: './output/'  #翻译好的双行文本所在的文件夹，这个文件夹不需要与extract.output.path一致
    encoding: 'utf16le-bom'
  output:
    path: './replaced/' #替换好的脚本会保存到这里
    encoding: 'utf16le-bom'

#常用的encoding: ['utf8', 'utf8-bom', 'utf16le', 'utf16le-bom', 'utf16be', 'utf16be-bom', 'shift-jis', 'gb2312', 'gbk'];
```

（第一行的  “ *chapter10_0|ガラパゴスの箱舟”在其他文件里均有类似如“*chapter7_0|スローターハウス” 等语句在第一行中，且其余文件均未报错）
